# Generated by Django 4.2.29 on 2026-03-20 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=5, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=15, unique=True, verbose_name='Clave')),
                ('subcategoria', models.IntegerField(default=0)),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('tipo_plaza', models.CharField(blank=True, max_length=50)),
                ('tp', models.CharField(blank=True, max_length=5)),
                ('nivel', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='CentroTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('nivel_educativo', models.CharField(blank=True, max_length=50)),
                ('municipio', models.CharField(blank=True, max_length=100)),
                ('domicilio', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Centro de Trabajo',
                'verbose_name_plural': 'Centros de Trabajo',
            },
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.IntegerField(default=2025, verbose_name='Ejercicio')),
                ('clave', models.CharField(max_length=5, verbose_name='Clave')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Dependencia',
                'verbose_name_plural': 'Dependencias',
                'ordering': ['clave'],
                'unique_together': {('ejercicio', 'clave')},
            },
        ),
        migrations.CreateModel(
            name='Discapacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.IntegerField(unique=True)),
                ('tipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Discapacidad',
                'verbose_name_plural': 'Discapacidades',
            },
        ),
        migrations.CreateModel(
            name='EnfermedadCronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.IntegerField(unique=True)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Enfermedad Crónica',
                'verbose_name_plural': 'Enfermedades Crónicas',
            },
        ),
        migrations.CreateModel(
            name='EntidadFederativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.IntegerField(unique=True)),
                ('abreviatura', models.CharField(max_length=5)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Entidad Federativa',
                'verbose_name_plural': 'Entidades Federativas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=5, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Estado Civil',
                'verbose_name_plural': 'Estados Civiles',
            },
        ),
        migrations.CreateModel(
            name='EstatusPlaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=5, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Estatus de Plaza',
                'verbose_name_plural': 'Estatus de Plaza',
            },
        ),
        migrations.CreateModel(
            name='FuenteFinanciamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10, unique=True, verbose_name='Clave')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Fuente de Financiamiento',
                'verbose_name_plural': 'Fuentes de Financiamiento',
                'ordering': ['clave'],
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.IntegerField(unique=True)),
                ('identificador_cndh', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('familia_linguistica', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Idioma/Lengua',
                'verbose_name_plural': 'Idiomas/Lenguas',
            },
        ),
        migrations.CreateModel(
            name='MotivoBaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=5, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Motivo de Baja',
                'verbose_name_plural': 'Motivos de Baja',
            },
        ),
        migrations.CreateModel(
            name='NivelEscolaridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.IntegerField(unique=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('estatus', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Nivel de Escolaridad',
                'verbose_name_plural': 'Niveles de Escolaridad',
            },
        ),
        migrations.CreateModel(
            name='NivelEstructura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=15, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('nivel', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Nivel de Estructura',
                'verbose_name_plural': 'Niveles de Estructura',
                'ordering': ['nivel'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.IntegerField(default=2025)),
                ('clave', models.CharField(max_length=10, verbose_name='Clave')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.dependencia')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
            },
        ),
        migrations.CreateModel(
            name='Pueblo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.IntegerField(unique=True)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Pueblo Indígena/Afromexicano',
                'verbose_name_plural': 'Pueblos Indígenas/Afromexicanos',
            },
        ),
        migrations.CreateModel(
            name='Sindicato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Sindicato',
                'verbose_name_plural': 'Sindicatos',
            },
        ),
        migrations.CreateModel(
            name='TipoContratacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=5, unique=True, verbose_name='Clave')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Contratación',
                'verbose_name_plural': 'Tipos de Contratación',
            },
        ),
        migrations.CreateModel(
            name='TipoDeclaracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=5, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Declaración',
                'verbose_name_plural': 'Tipos de Declaración',
            },
        ),
        migrations.CreateModel(
            name='TipoFuncion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=5, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Función',
                'verbose_name_plural': 'Tipos de Función',
            },
        ),
        migrations.CreateModel(
            name='UnidadAdministrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.IntegerField(default=2025)),
                ('clave', models.CharField(max_length=10, verbose_name='Clave')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.dependencia', verbose_name='Dependencia')),
            ],
            options={
                'verbose_name': 'Unidad Administrativa',
                'verbose_name_plural': 'Unidades Administrativas',
                'ordering': ['clave'],
            },
        ),
        migrations.CreateModel(
            name='TipoPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=5, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('tipo_contratacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogos.tipocontratacion')),
            ],
            options={
                'verbose_name': 'Tipo de Personal',
                'verbose_name_plural': 'Tipos de Personal',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.IntegerField(default=2025)),
                ('clave', models.CharField(max_length=20, verbose_name='Clave')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.dependencia')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.programa')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.unidadadministrativa')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.AddField(
            model_name='programa',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.unidadadministrativa'),
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abreviatura', models.CharField(blank=True, max_length=10)),
                ('clave', models.CharField(max_length=5)),
                ('nombre', models.CharField(max_length=100)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.entidadfederativa')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10, unique=True, verbose_name='Clave')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('calle', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(blank=True, max_length=100)),
                ('municipio', models.CharField(blank=True, max_length=100)),
                ('localidad', models.CharField(blank=True, max_length=100)),
                ('num_exterior', models.CharField(blank=True, max_length=10)),
                ('num_interior', models.CharField(blank=True, max_length=10)),
                ('colonia', models.CharField(blank=True, max_length=100)),
                ('cp', models.CharField(blank=True, max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('tipo_contrato', models.CharField(blank=True, choices=[('1', 'Propio'), ('2', 'Arrendamiento')], max_length=20)),
                ('superficie_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('superficie_construida', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.dependencia')),
            ],
            options={
                'verbose_name': 'Inmueble',
                'verbose_name_plural': 'Inmuebles',
            },
        ),
    ]
