# Generated by Django 6.0.3 on 2026-08-04 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='programa',
            unique_together={('ejercicio', 'dependencia', 'unidad', 'clave')},
        ),
        migrations.AlterUniqueTogether(
            name='proyecto',
            unique_together={('ejercicio', 'dependencia', 'unidad', 'programa', 'clave')},
        ),
        migrations.AlterUniqueTogether(
            name='unidadadministrativa',
            unique_together={('ejercicio', 'dependencia', 'clave')},
        ),
    ]
