# Generated by Django 6.0.3 on 2026-08-05 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0005_proyecto_remove_unidad_programa'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dependencia',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='programa',
            unique_together={('dependencia', 'unidad', 'clave')},
        ),
        migrations.AlterUniqueTogether(
            name='proyecto',
            unique_together={('dependencia', 'clave')},
        ),
        migrations.AlterUniqueTogether(
            name='unidadadministrativa',
            unique_together={('dependencia', 'clave')},
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='clave',
            field=models.CharField(max_length=5, unique=True, verbose_name='Clave'),
        ),
        migrations.RemoveField(
            model_name='dependencia',
            name='ejercicio',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='ejercicio',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='ejercicio',
        ),
        migrations.RemoveField(
            model_name='unidadadministrativa',
            name='ejercicio',
        ),
    ]
