# Generated by Django 6.0.3 on 2026-08-20 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0007_reemplazar_motivos_baja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalogo', models.CharField(max_length=30, verbose_name='Catálogo')),
                ('nombre_archivo', models.CharField(blank=True, max_length=255, verbose_name='Archivo')),
                ('estado', models.CharField(choices=[('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Error')], default='procesando', max_length=20)),
                ('creados', models.IntegerField(default=0)),
                ('actualizados', models.IntegerField(default=0)),
                ('errores', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('log', models.JSONField(blank=True, default=list)),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Importación de Catálogo',
                'verbose_name_plural': 'Importaciones de Catálogos',
                'ordering': ['-fecha'],
            },
        ),
    ]
