# Generated by Django 4.2.29 on 2026-03-20 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quincena', models.CharField(max_length=7, unique=True, verbose_name='Quincena (AAAA-QQ)')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio de carga')),
                ('fecha_fin', models.DateField(verbose_name='Fecha fin de carga')),
                ('activo', models.BooleanField(default=True, verbose_name='Período activo')),
            ],
            options={
                'verbose_name': 'Período de Carga',
                'verbose_name_plural': 'Períodos de Carga',
                'ordering': ['-quincena'],
            },
        ),
        migrations.CreateModel(
            name='CargaLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('basica', 'Información Básica'), ('personales', 'Datos Personales'), ('bajas', 'Bajas')], max_length=20, verbose_name='Tipo de Layout')),
                ('archivo', models.FileField(upload_to='cargas/', verbose_name='Archivo')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('con_errores', 'Con Errores')], default='pendiente', max_length=20)),
                ('registros_totales', models.IntegerField(default=0)),
                ('registros_ok', models.IntegerField(default=0)),
                ('registros_error', models.IntegerField(default=0)),
                ('log_errores', models.TextField(blank=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.dependencia', verbose_name='Dependencia')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cargas.periodocarga', verbose_name='Período')),
            ],
            options={
                'verbose_name': 'Carga de Layout',
                'verbose_name_plural': 'Cargas de Layouts',
                'ordering': ['-fecha_carga'],
            },
        ),
    ]
