# Generated by Django 6.0.3 on 2026-08-04 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0003_periodocarga_fecha_cierre'),
        ('catalogos', '0002_alter_programa_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoExcepcionCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio de acceso')),
                ('fecha_fin', models.DateField(verbose_name='Fecha fin de acceso')),
                ('motivo', models.CharField(blank=True, max_length=255, verbose_name='Motivo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autorizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autorizado por')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.dependencia', verbose_name='Dependencia')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excepciones', to='cargas.periodocarga', verbose_name='Período')),
            ],
            options={
                'verbose_name': 'Excepción de Acceso',
                'verbose_name_plural': 'Excepciones de Acceso',
                'ordering': ['-periodo', 'dependencia'],
                'unique_together': {('periodo', 'dependencia')},
            },
        ),
    ]
