# Generated by Django 6.0.3 on 2026-08-08 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0006_fecha_cierre_3_dias_habiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodocarga',
            name='fecha_cierre',
            field=models.DateField(editable=False, help_text='Calculada automáticamente: 3 días hábiles después de la fecha fin.', verbose_name='Fecha de cierre'),
        ),
    ]
