# Generated by Django 6.0.3 on 2026-08-12 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def marcar_completadas_como_aceptadas(apps, schema_editor):
    """Las cargas que bajo el flujo anterior quedaron en 'completado' ya se
    aplicaron de verdad al padrón, así que hoy equivalen a 'aceptado'."""
    CargaLayout = apps.get_model('cargas', 'CargaLayout')
    CargaLayout.objects.filter(estado='completado').update(estado='aceptado')


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0007_alter_periodocarga_fecha_cierre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cargalayout',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión'),
        ),
        migrations.AddField(
            model_name='cargalayout',
            name='motivo_rechazo',
            field=models.TextField(blank=True, verbose_name='Motivo de rechazo'),
        ),
        migrations.AddField(
            model_name='cargalayout',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargas_revisadas', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por'),
        ),
        migrations.AlterField(
            model_name='cargalayout',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('con_errores', 'Con Errores'), ('pendiente_revision', 'Pendiente de Revisión'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.RunPython(marcar_completadas_como_aceptadas, migrations.RunPython.noop),
    ]
