# Generated by Django 6.0.3 on 2026-08-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0008_cargalayout_fecha_revision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargalayout',
            name='detalle_filas',
            field=models.JSONField(blank=True, default=list, verbose_name='Detalle por registro'),
        ),
    ]
