# Generated by Django 6.0.3 on 2026-08-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0009_cargalayout_detalle_filas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargalayout',
            name='decisiones_filas',
            field=models.JSONField(blank=True, default=dict, help_text='Para filas con error "forzable" (p.ej. RFC/CURP con formato inválido): {"<num_fila>": {"decision": "aceptada"|"rechazada", "motivo": str, "por": str, "fecha": iso8601}}', verbose_name='Decisiones de revisión por fila'),
        ),
    ]
