# Generated by Django 6.0.3 on 2026-08-14 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0010_cargalayout_decisiones_filas'),
        ('catalogos', '0007_reemplazar_motivos_baja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesoexcepcioncarga',
            name='dependencia',
            field=models.ForeignKey(blank=True, help_text='Vacío = aplica a todas las dependencias.', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogos.dependencia', verbose_name='Dependencia'),
        ),
    ]
