# Generated by Django 6.0.3 on 2026-08-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioresp',
            name='rol',
            field=models.CharField(choices=[('plantilla', 'Operador'), ('validador', 'Validador'), ('empleado', 'Empleado'), ('consulta', 'Consulta'), ('oic', 'OIC'), ('general', 'General'), ('administrador', 'Administrador')], default='empleado', max_length=20, verbose_name='Rol'),
        ),
    ]
