# Generated by Django 6.0.3 on 2026-09-01 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuarioresp_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcionAplicativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, unique=True, verbose_name='Clave')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('modulo', models.CharField(max_length=50, verbose_name='Módulo')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Opción del Aplicativo',
                'verbose_name_plural': 'Opciones del Aplicativo',
                'ordering': ['orden', 'modulo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('plantilla', 'Operador'), ('validador', 'Validador'), ('empleado', 'Empleado'), ('consulta', 'Consulta'), ('oic', 'OIC'), ('general', 'General')], max_length=20, verbose_name='Rol')),
                ('permitido', models.BooleanField(default=False, verbose_name='Permitido')),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='usuarios.opcionaplicativo', verbose_name='Opción')),
            ],
            options={
                'verbose_name': 'Permiso de Rol',
                'verbose_name_plural': 'Permisos de Roles',
                'unique_together': {('rol', 'opcion')},
            },
        ),
    ]
