# Generated by Django 6.0.3 on 2026-09-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_seed_opciones_permisos'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcionaplicativo',
            name='tiene_edicion',
            field=models.BooleanField(default=False, help_text='Si además de "ver" esta opción se puede restringir por separado quién puede crear/editar dentro de ella (ver RolPermiso.puede_editar).', verbose_name='Tiene permiso de edición'),
        ),
        migrations.AddField(
            model_name='rolpermiso',
            name='puede_editar',
            field=models.BooleanField(default=False, help_text='Solo aplica si la opción tiene edición configurable. Sin esto, el rol solo puede consultar — no crear ni modificar registros.', verbose_name='Puede editar'),
        ),
        migrations.AlterField(
            model_name='rolpermiso',
            name='permitido',
            field=models.BooleanField(default=False, verbose_name='Permitido (ver)'),
        ),
    ]
