# Generated by Django 4.2.29 on 2026-03-20 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServidorPublico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediente', models.CharField(max_length=20, unique=True, verbose_name='No. Expediente')),
                ('rfc', models.CharField(max_length=13, unique=True, verbose_name='RFC')),
                ('curp', models.CharField(max_length=18, unique=True, verbose_name='CURP')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre(s)')),
                ('primer_apellido', models.CharField(max_length=50, verbose_name='Primer Apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo Apellido')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('sexo', models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino'), ('OTRO', 'Otro')], max_length=10, verbose_name='Sexo')),
                ('correo_institucional', models.EmailField(blank=True, max_length=254, verbose_name='Correo Institucional')),
                ('iss', models.CharField(choices=[('ISSET', 'ISSET'), ('IMSS', 'IMSS'), ('ISSSTE', 'ISSSTE'), ('NINGUNO', 'Ninguno')], default='ISSET', max_length=10, verbose_name='Instituto de Seguridad Social')),
                ('nss', models.CharField(blank=True, max_length=20, verbose_name='Número de Seguridad Social')),
                ('sindicalizado', models.CharField(choices=[('S', 'Sí'), ('N', 'No'), ('NULL', 'No aplica')], default='N', max_length=5, verbose_name='¿Sindicalizado?')),
                ('tiene_otra_plaza', models.CharField(choices=[('S', 'Sí'), ('N', 'No'), ('NULL', 'No aplica')], default='N', max_length=5, verbose_name='¿Tiene otra plaza?')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('entidad_nacimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.entidadfederativa', verbose_name='Entidad de Nacimiento')),
                ('estado_civil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.estadocivil', verbose_name='Estado Civil')),
                ('pais_nacimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.pais', verbose_name='País de Nacimiento')),
                ('sindicato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.sindicato', verbose_name='Sindicato')),
            ],
            options={
                'verbose_name': 'Servidor Público',
                'verbose_name_plural': 'Servidores Públicos',
                'ordering': ['primer_apellido', 'segundo_apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='InformacionBasica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_plaza', models.CharField(max_length=20, verbose_name='ID Plaza')),
                ('puesto', models.CharField(max_length=20, verbose_name='Puesto')),
                ('id_plaza_jefe', models.CharField(blank=True, max_length=20, verbose_name='ID Plaza Jefe Inmediato')),
                ('puesto_jefe', models.CharField(blank=True, max_length=20, verbose_name='Puesto Jefe Inmediato')),
                ('hsm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='HSM (Hora-Semana-Mes)')),
                ('total_percepciones', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Percepciones')),
                ('total_bonos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Bonos')),
                ('total_neto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Neto')),
                ('dias_pagados', models.IntegerField(default=0, verbose_name='Días Pagados')),
                ('oblig_declaracion', models.CharField(choices=[('S', 'Sí'), ('N', 'No'), ('NULL', 'No aplica')], default='N', max_length=5, verbose_name='Obligado a Declaración Patrimonial')),
                ('oblig_entrega_recepcion', models.CharField(choices=[('S', 'Sí'), ('N', 'No'), ('NULL', 'No aplica')], default='N', max_length=5, verbose_name='Oblig. Acta Entrega-Recepción')),
                ('oblig_rendir_cuentas', models.CharField(choices=[('S', 'Sí'), ('N', 'No'), ('NULL', 'No aplica')], default='N', max_length=5, verbose_name='Obligado a Rendir Cuentas')),
                ('puesto_sensible', models.CharField(choices=[('S', 'Sí'), ('N', 'No'), ('NULL', 'No aplica')], default='N', max_length=5, verbose_name='Puesto con Info. Sensible')),
                ('fecha_ingreso_gobierno', models.DateField(blank=True, null=True, verbose_name='Fecha Ingreso al Gobierno')),
                ('fecha_ingreso_dependencia', models.DateField(blank=True, null=True, verbose_name='Fecha Ingreso a la Dependencia')),
                ('fecha_ingreso_puesto', models.DateField(blank=True, null=True, verbose_name='Fecha Ingreso al Puesto')),
                ('participa_contrataciones', models.CharField(choices=[('S', 'Sí'), ('N', 'No'), ('NULL', 'No aplica')], default='N', max_length=5, verbose_name='Participa en Contrataciones')),
                ('nivel_contrataciones', models.CharField(blank=True, max_length=10, verbose_name='Nivel en Contrataciones')),
                ('participa_concesiones', models.CharField(choices=[('S', 'Sí'), ('N', 'No'), ('NULL', 'No aplica')], default='N', max_length=5, verbose_name='Participa en Concesiones')),
                ('nivel_concesiones', models.CharField(blank=True, max_length=10, verbose_name='Nivel en Concesiones')),
                ('participa_enajenacion', models.CharField(choices=[('S', 'Sí'), ('N', 'No'), ('NULL', 'No aplica')], default='N', max_length=5, verbose_name='Participa en Enajenación')),
                ('nivel_enajenacion', models.CharField(blank=True, max_length=10, verbose_name='Nivel en Enajenación')),
                ('participa_avaluos', models.CharField(choices=[('S', 'Sí'), ('N', 'No'), ('NULL', 'No aplica')], default='N', max_length=5, verbose_name='Participa en Avalúos')),
                ('nivel_avaluos', models.CharField(blank=True, max_length=10, verbose_name='Nivel en Avalúos')),
                ('serc', models.CharField(choices=[('S', 'Sí'), ('N', 'No'), ('NULL', 'No aplica')], default='N', max_length=5, verbose_name='SERC')),
                ('exigibilidad_serc', models.CharField(choices=[('S', 'Sí'), ('N', 'No'), ('NULL', 'No aplica')], default='N', max_length=5, verbose_name='Exigibilidad SERC')),
                ('quincena', models.CharField(max_length=7, verbose_name='Quincena (AAAA-QQ)')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.area', verbose_name='Área')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.categoria', verbose_name='Categoría')),
                ('cct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.centrotrabajo', verbose_name='Centro de Trabajo')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.dependencia', verbose_name='Dependencia')),
                ('estatus_plaza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.estatusplaza', verbose_name='Estatus de Plaza')),
                ('fuente_financiamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.fuentefinanciamiento', verbose_name='Fuente de Financiamiento')),
                ('inmueble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.inmueble', verbose_name='Inmueble')),
                ('nivel_estructura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.nivelestructura', verbose_name='Nivel de Estructura')),
                ('nombramiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.tipocontratacion', verbose_name='Tipo de Contratación')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.programa', verbose_name='Programa')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.proyecto', verbose_name='Proyecto')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informacion_basica', to='servidores.servidorpublico', verbose_name='Servidor Público')),
                ('tipo_declaracion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.tipodeclaracion', verbose_name='Tipo de Declaración')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.unidadadministrativa', verbose_name='Unidad Administrativa')),
            ],
            options={
                'verbose_name': 'Información Básica',
                'verbose_name_plural': 'Información Básica',
                'ordering': ['-quincena', 'dependencia', 'servidor'],
            },
        ),
        migrations.CreateModel(
            name='IdiomaServidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(blank=True, max_length=20)),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.idioma')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idiomas', to='servidores.servidorpublico')),
            ],
        ),
        migrations.CreateModel(
            name='EnfermedadCronicaServidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.enfermedadcronica')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfermedades', to='servidores.servidorpublico')),
            ],
        ),
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(blank=True, max_length=100, verbose_name='Calle y Número')),
                ('num_exterior', models.CharField(blank=True, max_length=10, verbose_name='Núm. Exterior')),
                ('num_interior', models.CharField(blank=True, max_length=10, verbose_name='Núm. Interior')),
                ('colonia', models.CharField(blank=True, max_length=50, verbose_name='Colonia')),
                ('cp', models.CharField(blank=True, max_length=10, verbose_name='C.P.')),
                ('correo_personal', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Personal')),
                ('tipo_sangre', models.CharField(blank=True, max_length=4, verbose_name='Tipo de Sangre')),
                ('factor_rh', models.CharField(blank=True, choices=[('Positivo', 'Positivo'), ('Negativo', 'Negativo')], max_length=10, verbose_name='Factor RH')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('entidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.entidadfederativa', verbose_name='Entidad Federativa')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.municipio', verbose_name='Municipio')),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.pais', verbose_name='País')),
                ('servidor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_personales', to='servidores.servidorpublico')),
            ],
            options={
                'verbose_name': 'Datos Personales',
                'verbose_name_plural': 'Datos Personales',
            },
        ),
        migrations.CreateModel(
            name='DatosComplementarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validado', models.BooleanField(default=False, verbose_name='Validado')),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('discapacidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.discapacidad', verbose_name='Discapacidad')),
                ('nivel_escolaridad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.nivelescolaridad', verbose_name='Nivel de Escolaridad')),
                ('pueblo_indigena', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.pueblo', verbose_name='Pueblo Indígena/Afromexicano')),
                ('servidor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_complementarios', to='servidores.servidorpublico')),
            ],
            options={
                'verbose_name': 'Datos Complementarios',
                'verbose_name_plural': 'Datos Complementarios',
            },
        ),
        migrations.CreateModel(
            name='BajaServidorPublico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_baja', models.DateField(verbose_name='Fecha de Baja')),
                ('ejercicio', models.IntegerField(verbose_name='Ejercicio')),
                ('periodo', models.CharField(max_length=7, verbose_name='Período')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.dependencia')),
                ('motivo_baja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.motivobaja', verbose_name='Motivo de Baja')),
            ],
            options={
                'verbose_name': 'Baja de Servidor Público',
                'verbose_name_plural': 'Bajas de Servidores Públicos',
            },
        ),
    ]
