# Generated by Django 4.2.29 on 2026-03-20 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servidores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bajaservidorpublico',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bajaservidorpublico',
            name='servidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bajas', to='servidores.servidorpublico'),
        ),
        migrations.AlterUniqueTogether(
            name='idiomaservidor',
            unique_together={('servidor', 'idioma')},
        ),
        migrations.AlterUniqueTogether(
            name='enfermedadcronicaservidor',
            unique_together={('servidor', 'enfermedad')},
        ),
    ]
