# Generated by Django 6.0.3 on 2026-08-04 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_alter_programa_unique_together_and_more'),
        ('servidores', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_plaza', models.CharField(max_length=20, verbose_name='ID de Plaza')),
                ('estatus', models.CharField(choices=[('vacante', 'Vacante'), ('ocupada', 'Ocupada')], default='vacante', editable=False, max_length=10, verbose_name='Estatus')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.categoria', verbose_name='Categoría')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='puestos', to='catalogos.proyecto', verbose_name='Proyecto')),
                ('servidor_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puestos_ocupados', to='servidores.servidorpublico', verbose_name='Trabajador Asignado')),
            ],
            options={
                'verbose_name': 'Puesto',
                'verbose_name_plural': 'Puestos',
                'ordering': ['proyecto', 'id_plaza'],
                'unique_together': {('proyecto', 'id_plaza')},
            },
        ),
    ]
