# Generated by Django 6.0.3 on 2026-08-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0003_puesto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='puesto',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='id_plaza',
            field=models.CharField(max_length=20, unique=True, verbose_name='ID de Plaza'),
        ),
    ]
