# Generated by Django 6.0.3 on 2026-08-05 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0005_puesto_programa'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidorpublico',
            name='determinante',
            field=models.CharField(blank=True, max_length=20, verbose_name='Determinante'),
        ),
    ]
