# Generated by Django 6.0.3 on 2026-08-06 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_alter_dependencia_unique_together_and_more'),
        ('servidores', '0006_servidorpublico_determinante'),
    ]

    operations = [
        migrations.AddField(
            model_name='puesto',
            name='cct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.centrotrabajo', verbose_name='Centro de Trabajo'),
        ),
        migrations.AddField(
            model_name='puesto',
            name='dias_pagados',
            field=models.IntegerField(default=0, verbose_name='Días Pagados'),
        ),
        migrations.AddField(
            model_name='puesto',
            name='estatus_plaza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.estatusplaza', verbose_name='Estatus de Plaza'),
        ),
        migrations.AddField(
            model_name='puesto',
            name='hsm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='HSM (Hora-Semana-Mes)'),
        ),
        migrations.AddField(
            model_name='puesto',
            name='nivel_estructura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.nivelestructura', verbose_name='Nivel de Estructura'),
        ),
        migrations.AddField(
            model_name='puesto',
            name='nombramiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.tipocontratacion', verbose_name='Tipo de Contratación'),
        ),
        migrations.AddField(
            model_name='puesto',
            name='total_bonos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Bonos'),
        ),
        migrations.AddField(
            model_name='puesto',
            name='total_neto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Neto'),
        ),
        migrations.AddField(
            model_name='puesto',
            name='total_percepciones',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Percepciones'),
        ),
        migrations.AddField(
            model_name='puesto',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.unidadadministrativa', verbose_name='Unidad Administrativa'),
        ),
    ]
