# Generated by Django 6.0.3 on 2026-08-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0007_puesto_cct_puesto_dias_pagados_puesto_estatus_plaza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puesto',
            name='id_plaza_jefe',
            field=models.CharField(blank=True, max_length=20, verbose_name='ID Plaza Jefe Inmediato'),
        ),
    ]
