# Generated by Django 6.0.3 on 2026-08-06 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0008_puesto_id_plaza_jefe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puesto',
            name='estatus',
        ),
    ]
