# Generated by Django 6.0.3 on 2026-08-07 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_alter_dependencia_unique_together_and_more'),
        ('servidores', '0009_remove_puesto_estatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puesto',
            options={'ordering': ['proyecto', 'id_plaza'], 'verbose_name': 'Plaza', 'verbose_name_plural': 'Plazas'},
        ),
        migrations.RemoveField(
            model_name='datoscomplementarios',
            name='discapacidad',
        ),
        migrations.CreateModel(
            name='DiscapacidadServidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discapacidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.discapacidad')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discapacidades', to='servidores.servidorpublico')),
            ],
            options={
                'unique_together': {('servidor', 'discapacidad')},
            },
        ),
    ]
