# Generated by Django 6.0.3 on 2026-08-12 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0007_reemplazar_motivos_baja'),
        ('servidores', '0010_alter_puesto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionbasica',
            name='tipo_funcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.tipofuncion', verbose_name='Tipo de Función'),
        ),
        migrations.AddField(
            model_name='informacionbasica',
            name='tipo_personal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.tipopersonal', verbose_name='Tipo de Personal'),
        ),
    ]
