# Generated by Django 6.0.3 on 2026-08-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0011_informacionbasica_tipo_funcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bajaservidorpublico',
            name='id_plaza',
            field=models.CharField(blank=True, help_text='Plaza que se libera con esta baja (la carga de layout la exige; el alta manual libera todas las plazas del servidor).', max_length=20, verbose_name='ID de Plaza'),
        ),
    ]
