# Generated by Django 6.0.3 on 2026-08-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0012_bajaservidorpublico_id_plaza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidorpublico',
            name='sexo',
            field=models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino'), ('OTRO', 'Otro')], max_length=10, verbose_name='Género'),
        ),
    ]
