# Generated by Django 6.0.3 on 2026-08-31 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0011_alter_accesoexcepcioncarga_dependencia'),
        ('servidores', '0013_alter_servidorpublico_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionbasica',
            name='carga_origen',
            field=models.ForeignKey(blank=True, help_text='Carga de layout que creó/actualizó este registro. Vacío en registros de antes de esta función o dados de alta manualmente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_generados', to='cargas.cargalayout', verbose_name='Carga de origen'),
        ),
    ]
