# Generated by Django 6.0.3 on 2026-08-31 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0011_alter_accesoexcepcioncarga_dependencia'),
        ('servidores', '0014_informacionbasica_carga_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='bajaservidorpublico',
            name='carga_origen',
            field=models.ForeignKey(blank=True, help_text='Carga de layout que registró esta baja. Vacío si se dio de alta manualmente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bajas_generadas', to='cargas.cargalayout', verbose_name='Carga de origen'),
        ),
    ]
