# Generated by Django 6.0.3 on 2026-08-31 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0011_alter_accesoexcepcioncarga_dependencia'),
        ('servidores', '0015_bajaservidorpublico_carga_origen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(choices=[('informacion_basica', 'Información Básica'), ('baja', 'Baja de Servidor Público'), ('datos_personales', 'Datos Personales')], max_length=30, verbose_name='Modelo')),
                ('objeto_id', models.PositiveIntegerField(verbose_name='ID del registro')),
                ('accion', models.CharField(choices=[('creado', 'Creado'), ('editado', 'Editado')], max_length=10, verbose_name='Acción')),
                ('origen', models.CharField(choices=[('carga', 'Carga de Layout'), ('manual', 'Manual')], max_length=10, verbose_name='Origen')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('carga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cargas.cargalayout', verbose_name='Carga')),
                ('servidor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_log', to='servidores.servidorpublico', verbose_name='Servidor')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Evento de Log',
                'verbose_name_plural': 'Log de Eventos',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['modelo', 'objeto_id'], name='servidores__modelo_26d039_idx')],
            },
        ),
    ]
