# Generated by Django 6.0.3 on 2026-09-02 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0008_importacioncatalogo'),
        ('servidores', '0016_logevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionbasica',
            name='correo_institucional',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo Institucional (del periodo)'),
        ),
        migrations.AddField(
            model_name='informacionbasica',
            name='curp',
            field=models.CharField(blank=True, max_length=18, verbose_name='CURP (del periodo)'),
        ),
        migrations.AddField(
            model_name='informacionbasica',
            name='determinante',
            field=models.CharField(blank=True, max_length=20, verbose_name='Determinante (del periodo)'),
        ),
        migrations.AddField(
            model_name='informacionbasica',
            name='entidad_nacimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informacion_basica_periodo', to='catalogos.entidadfederativa', verbose_name='Entidad de Nacimiento (del periodo)'),
        ),
        migrations.AddField(
            model_name='informacionbasica',
            name='estado_civil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informacion_basica_periodo', to='catalogos.estadocivil', verbose_name='Estado Civil (del periodo)'),
        ),
        migrations.AddField(
            model_name='informacionbasica',
            name='expediente',
            field=models.CharField(blank=True, max_length=20, verbose_name='No. Expediente (del periodo)'),
        ),
        migrations.AddField(
            model_name='informacionbasica',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento (del periodo)'),
        ),
        migrations.AddField(
            model_name='informacionbasica',
            name='iss',
            field=models.CharField(blank=True, choices=[('ISSET', 'ISSET'), ('IMSS', 'IMSS'), ('ISSSTE', 'ISSSTE'), ('NINGUNO', 'Ninguno')], max_length=10, verbose_name='Instituto de Seguridad Social (del periodo)'),
        ),
        migrations.AddField(
            model_name='informacionbasica',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nombre(s) (del periodo)'),
        ),
        migrations.AddField(
            model_name='informacionbasica',
            name='nss',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número de Seguridad Social (del periodo)'),
        ),
        migrations.AddField(
            model_name='informacionbasica',
            name='pais_nacimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informacion_basica_periodo', to='catalogos.pais', verbose_name='País de Nacimiento (del periodo)'),
        ),
        migrations.AddField(
            model_name='informacionbasica',
            name='primer_apellido',
            field=models.CharField(blank=True, max_length=50, verbose_name='Primer Apellido (del periodo)'),
        ),
        migrations.AddField(
            model_name='informacionbasica',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, verbose_name='RFC (del periodo)'),
        ),
        migrations.AddField(
            model_name='informacionbasica',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=50, verbose_name='Segundo Apellido (del periodo)'),
        ),
        migrations.AddField(
            model_name='informacionbasica',
            name='sexo',
            field=models.CharField(blank=True, choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino'), ('OTRO', 'Otro')], max_length=10, verbose_name='Género (del periodo)'),
        ),
        migrations.AddField(
            model_name='informacionbasica',
            name='sindicalizado',
            field=models.CharField(blank=True, choices=[('S', 'Sí'), ('N', 'No'), ('NULL', 'No aplica')], max_length=5, verbose_name='¿Sindicalizado? (del periodo)'),
        ),
        migrations.AddField(
            model_name='informacionbasica',
            name='sindicato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informacion_basica_periodo', to='catalogos.sindicato', verbose_name='Sindicato (del periodo)'),
        ),
        migrations.AddField(
            model_name='informacionbasica',
            name='tiene_otra_plaza',
            field=models.CharField(blank=True, choices=[('S', 'Sí'), ('N', 'No'), ('NULL', 'No aplica')], max_length=5, verbose_name='¿Tiene otra plaza? (del periodo)'),
        ),
    ]
